# Base clothing that can be equipped without removing a coat or similar outer clothing
- type: entity
  id: ClothingUniformShirtlessBase
  abstract: true
  components:
  - type: Tag
    tags:
    - ClothMade
    - WhitelistChameleon
    - ShirtlessClothing # to allow equipping/unequipping under coats and the like

# Base clothing that does not block undergarment slots
- type: entity
  id: ClothingUniformShirtlessAccessibleBase
  abstract: true
  components:
  - type: Tag
    tags:
    - ClothMade
    - WhitelistChameleon
    - Skirt #DeltaV, needed for species with nonhuman legs/can only wear skirts
    - ShirtlessClothing
    - BottomAccessibleClothing
    
# Base clothing that does not block undergarment slots
- type: entity
  id: ClothingUniformNakedBase
  abstract: true
  components:
  - type: Tag
    tags:
    - ClothMade
    - WhitelistChameleon
    - Skirt #DeltaV, needed for species with nonhuman legs/can only wear skirts
    - ShirtlessClothing
    - BottomlessClothing

# Base undergarment. Do not inherit from this directly.
- type: entity
  abstract: true
  parent: Clothing
  id: ClothingUndergarmentBase
  components:
  - type: EmitSoundOnPickup # Goob's interaction sounds.
    sound:
      path: /Audio/_Goobstation/Items/handling/generic_small_pickup.ogg
      params:
        volume: -8
  - type: EmitSoundOnDrop
    sound: &garment_drop_sound
      path: /Audio/_Goobstation/Items/handling/shoes_drop.ogg
      params:
        volume: -8
  - type: EmitSoundOnLand
    sound: *garment_drop_sound
  - type: Item
    size: Small
    shape:
    - 0,0,1,0 # 1x2
  - type: Edible
    requiresSpecialDigestion: true
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: Fiber
          Quantity: 5
  - type: Butcherable
    butcheringType: Knife
    spawned:
    - id: MaterialCloth1 # Very little
      amount: 1
  - type: PhysicalComposition # 50% of the amount of cloth you'd obtain upon butchering
    materialComposition:
      Cloth: 50
  - type: Sprite
    state: icon
  - type: Clothing
    equipSound:
      collection: GenericEquip
      params:
        volume: -8
  - type: Tag
    tags:
    - ClothMade
    - Recyclable


# Base for bottom undergarment
- type: entity
  abstract: true
  parent: ClothingUndergarmentBase
  id: ClothingUndergarmentBottomBase
  components:
  - type: Clothing
    slots:
    - UNDERGARMENT_BOTTOM
    clothingVisuals:
      undergarmentBottom:
      - state: equipped-INNERCLOTHING # Terrible hack cause i can't be bothered to rename all the items' sprites
  - type: SlotBlocker # Floofstation
    blockedBy:
      slots:
      - INNERCLOTHING
      - OUTERCLOTHING
      blacklist:
        tags:
        - BottomlessClothing
        - BottomAccessibleClothing

# Base for top undergarment
- type: entity
  abstract: true
  parent: ClothingUndergarmentBase
  id: ClothingUndergarmentTopBase
  components:
  - type: Clothing
    slots:
    - UNDERGARMENT_TOP
    clothingVisuals:
      undergarmentTop:
      - state: equipped-INNERCLOTHING # Terrible hack cause i can't be bothered to rename all the items' sprites
  - type: SlotBlocker # Floofstation
    blockedBy:
      slots:
      - INNERCLOTHING
      - OUTERCLOTHING
      blacklist:
        tags:
        - ShirtlessClothing

# Base for socks
- type: entity
  abstract: true
  parent: ClothingUndergarmentBase
  id: ClothingUndergarmentSocksBase
  components:
  - type: Clothing
    slots:
    - UNDERGARMENT_SOCKS
    clothingVisuals:
      undergarmentSocks:
      - state: equipped-FEET # Terrible hack cause i can't be bothered to rename all the items' sprites
  - type: SlotBlocker # Floofstation
    blockedBy:
      slots:
      - FEET



# Base for top undergarment that can also be equipped in inner or outer clothing
- type: entity
  abstract: true
  parent: ClothingUndergarmentTopBase
  id: ClothingUndergarmentTopSwitchableBase
  components:
  - type: Clothing
    slots:
    - INNERCLOTHING
    - OUTERCLOTHING
    - UNDERGARMENT_TOP
  - type: SlotBlocker # Floofstation
    blockedBy:
      slots:
      - OUTERCLOTHING
      blacklist:
        tags:
        - ShirtlessClothing
