using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._HL.Brainwashing.CompulsionsUI;

[GenerateTypedNameReferences]
public sealed partial class BrainwashMenu : FancyWindow
{
    public BrainwashMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Populate(List<(string, bool)> compulsions)
    {
        CompulsionDisplayContainer.Children.Clear();

        foreach (var compulsion in compulsions)
        {
            if (compulsion.Item2)
            {
                CompulsionDisplayContainer.AddChild(new CompulsionDisplay(compulsion.Item1));
            }
        }
    }
}
