using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._HL.Brainwashing.CompulsionsUI.EditUI;

[GenerateTypedNameReferences]
public sealed partial class BrainwashEui : FancyWindow
{
    private List<string> _compulsions = [];

    public BrainwashEui()
    {
        RobustXamlLoader.Load(this);
        NewCompulsionButton.OnPressed += _ => AddNewCompulsion();
    }

    private void AddNewCompulsion()
    {
        _compulsions = GetCompulsions();
        _compulsions.Add("");
        SetCompulsions(_compulsions);
    }

    public List<string> GetCompulsions()
    {
        var newCompulsions = new List<string>();

        foreach (var control in CompulsionContainer.Children)
        {
            if (control is not CompulsionContainer compulsionControl || !compulsionControl.IsSelected)
                continue;

            var compulsionText = Rope.Collapse(compulsionControl.CompulsionContent.TextRope).Trim();

            if (string.IsNullOrWhiteSpace(compulsionText))
                continue;

            newCompulsions.Add(compulsionText);
        }

        return newCompulsions;
    }

    private void MoveUp(int index)
    {
        if (index <= 0)
            return;

        _compulsions = GetCompulsions();
        (_compulsions[index], _compulsions[index - 1]) = (_compulsions[index - 1], _compulsions[index]);
        SetCompulsions(_compulsions);
    }

    private void MoveDown(int index)
    {
        if (index >= _compulsions.Count - 1)
            return;

        _compulsions = GetCompulsions();
        (_compulsions[index], _compulsions[index + 1]) = (_compulsions[index + 1], _compulsions[index]);
        SetCompulsions(_compulsions);
    }

    private void ToggleActive(int index)
    {
        Console.WriteLine(_compulsions[index]);
        _compulsions = GetCompulsions();

        SetCompulsions(_compulsions);
    }

    private void Delete(int index)
    {
        _compulsions = GetCompulsions();
        _compulsions.RemoveAt(index);

        SetCompulsions(_compulsions);
    }

    public void SetCompulsions(List<string> compulsions)
    {
        _compulsions = compulsions;
        CompulsionContainer.RemoveAllChildren();
        for (var i = 0; i < compulsions.Count; i++)
        {
            var index = i;
            var compulsion = compulsions[i];
            var compulsionControl = new CompulsionContainer(compulsion);
            compulsionControl.MoveUp.OnPressed += _ => MoveUp(index);
            compulsionControl.MoveDown.OnPressed += _ => MoveDown(index);
            compulsionControl.IsActiveCheckbox.OnToggled += _ => ToggleActive(index);
            compulsionControl.Delete.OnPressed += _ => Delete(index);
            CompulsionContainer.AddChild(compulsionControl);
        }
    }
}
