using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._HL.Brainwashing.CompulsionsUI.EditUI;

[GenerateTypedNameReferences]
public sealed partial class BrainwashEui : FancyWindow
{
    private List<(string, bool)> _compulsions = [];

    public BrainwashEui()
    {
        RobustXamlLoader.Load(this);
        NewCompulsionButton.OnPressed += _ => AddNewCompulsion();
    }

    private void AddNewCompulsion()
    {
        _compulsions = GetCompulsions();
        _compulsions.Add(("", false));
        SetCompulsions(_compulsions);
    }

    public List<(string, bool)> GetCompulsions()
    {
        var newCompulsions = new List<(string, bool)>();

        foreach (var control in CompulsionContainer.Children)
        {
            if (control is not CompulsionContainer compulsionControl)
                continue;

            var compulsionText = Rope.Collapse(compulsionControl.CompulsionContent.TextRope).Trim();

            if (string.IsNullOrWhiteSpace(compulsionText))
                continue;

            newCompulsions.Add((compulsionText, compulsionControl.IsSelected));
        }

        return newCompulsions;
    }

    private void MoveUp(int index)
    {
        if (index <= 0)
            return;

        _compulsions = GetCompulsions();
        (_compulsions[index], _compulsions[index - 1]) = (_compulsions[index - 1], _compulsions[index]);
        SetCompulsions(_compulsions);
    }

    private void MoveDown(int index)
    {
        if (index >= _compulsions.Count - 1)
            return;

        _compulsions = GetCompulsions();
        (_compulsions[index], _compulsions[index + 1]) = (_compulsions[index + 1], _compulsions[index]);
        SetCompulsions(_compulsions);
    }

    private void ToggleActive(int index)
    {
        //todo: this has index out of bounds error :( why? let's find out
        _compulsions = GetCompulsions();
        _compulsions[index] = (_compulsions[index].Item1, !_compulsions[index].Item2);
        SetCompulsions(_compulsions);
    }

    private void Delete(int index)
    {
        _compulsions = GetCompulsions();
        _compulsions.RemoveAt(index);

        SetCompulsions(_compulsions);
    }

    public void SetCompulsions(List<(string, bool)> compulsions)
    {
        _compulsions = compulsions;
        CompulsionContainer.RemoveAllChildren();
        for (var i = 0; i < compulsions.Count; i++)
        {
            var index = i;
            var compulsion = compulsions[i];
            var compulsionControl = new CompulsionContainer(compulsion.Item1);
            compulsionControl.MoveUp.OnPressed += _ => MoveUp(index);
            compulsionControl.MoveDown.OnPressed += _ => MoveDown(index);
            compulsionControl.IsActiveCheckbox.OnPressed += _ => ToggleActive(index);
            compulsionControl.Delete.OnPressed += _ => Delete(index);
            CompulsionContainer.AddChild(compulsionControl);
        }
    }
}
