using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;


namespace Content.Client._HL.Brainwashing.CompulsionsUI.EditUI;

[GenerateTypedNameReferences]
public sealed partial class CompulsionContainer : BoxContainer
{
    public bool IsSelected => IsActiveCheckbox.Pressed;
    public CompulsionContainer(string? compulsion = null)
    {
        RobustXamlLoader.Load(this);

        if (compulsion != null)
        {
            CompulsionContent.TextRope = new Rope.Leaf(compulsion);
        }
    }
}
